//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImporterPOS.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImporterPOS.WPF.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikli.
        /// </summary>
        internal static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista je uspješno ispražnjena..
        /// </summary>
        internal static string ClearList {
            get {
                return ResourceManager.GetString("ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentExcelFile.
        /// </summary>
        internal static string CurrentExcelFile {
            get {
                return ResourceManager.GetString("CurrentExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentExcelSheet.
        /// </summary>
        internal static string CurrentExcelSheet {
            get {
                return ResourceManager.GetString("CurrentExcelSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna stranica.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popusti.
        /// </summary>
        internal static string Discounts {
            get {
                return ResourceManager.GetString("Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dogodila se pogreška. Pokušajte ponovo..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaš Excel file nije odgovarajućeg formata. Provjerite ga..
        /// </summary>
        internal static string ExcelFileError {
            get {
                return ResourceManager.GetString("ExcelFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dogodio se problem prilikom integracije u bazu podataka. Pokušajte ponovo..
        /// </summary>
        internal static string ImportArticlesError {
            get {
                return ResourceManager.GetString("ImportArticlesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završeno! Artikli su uspješno integrirani u bazu podataka..
        /// </summary>
        internal static string ImportArticlesSuccess {
            get {
                return ResourceManager.GetString("ImportArticlesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventurni dokumenti.
        /// </summary>
        internal static string InventoryDocuments {
            get {
                return ResourceManager.GetString("InventoryDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikli su uspješno učitani i pripremljeni za integraciju u softver..
        /// </summary>
        internal static string LoadDataSuccess {
            get {
                return ResourceManager.GetString("LoadDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite Excel file.
        /// </summary>
        internal static string OpenDialogTitle {
            get {
                return ResourceManager.GetString("OpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o popustu nisu postavljene. Unesite ih prije nastavka..
        /// </summary>
        internal static string OptionsRequired {
            get {
                return ResourceManager.GetString("OptionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file je uspješno odabran..
        /// </summary>
        internal static string SelectExcelFileSuccess {
            get {
                return ResourceManager.GetString("SelectExcelFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nešto nije uredu sa vašim fajlom. Pokušajte ponovo..
        /// </summary>
        internal static string SelectSheetError {
            get {
                return ResourceManager.GetString("SelectSheetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno odabran sheet..
        /// </summary>
        internal static string SelectSheetSuccess {
            get {
                return ResourceManager.GetString("SelectSheetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke nisu podešene..
        /// </summary>
        internal static string SettingsError {
            get {
                return ResourceManager.GetString("SettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skladišta.
        /// </summary>
        internal static string Storages {
            get {
                return ResourceManager.GetString("Storages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file je uspješno izmijenjen..
        /// </summary>
        internal static string UpdatedExcelFile {
            get {
                return ResourceManager.GetString("UpdatedExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabrali ste isti file..
        /// </summary>
        internal static string UpdatedSameFile {
            get {
                return ResourceManager.GetString("UpdatedSameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno otpisana roba..
        /// </summary>
        internal static string WritedOffSuccessfully {
            get {
                return ResourceManager.GetString("WritedOffSuccessfully", resourceCulture);
            }
        }
    }
}
